import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class DocumentService {
  Future<void> generateAndShareInvoice(Map<String, dynamic> sale) async {
    final pdf = pw.Document();
    final date = DateTime.fromMillisecondsSinceEpoch(sale['created_at'] as int);
    final isQuote = sale['status'] == 'QUOTATION';
    final title = isQuote ? 'QUOTATION' : 'INVOICE';
    final idPrefix = isQuote ? 'QUO' : 'INV';

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('SmartBiz Pro', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue600)),
                      pw.Text('Your Professional Business Partner'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(title, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                      pw.Text('#$idPrefix-${sale['id'].toString().substring(0, 8).toUpperCase()}'),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Bill To:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text(sale['customer_name'] ?? 'Cash Customer'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Date:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text(DateFormat('MMM dd, yyyy').format(date)),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 30),
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blue600),
                headers: ['Description', 'Qty', 'Unit Price', 'Total'],
                data: [
                  ['Business Transaction', '1', 'TZS ${sale['total_amount']}', 'TZS ${sale['total_amount']}'],
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Total Amount:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      pw.Text('TZS ${sale['total_amount']}', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue600)),
                    ],
                  ),
                ],
              ),
              pw.Spacer(),
              pw.Divider(),
              pw.Center(child: pw.Text('Thank you for your business!')),
              pw.Center(child: pw.Text('Generated by SmartBiz Pro Mobile', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey))),
            ],
          );
        },
      ),
    );

    final bytes = await pdf.save();
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$idPrefix-${sale['id']}.pdf');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles([XFile(file.path)], text: 'Here is your $title');
  }

  Future<void> generateAndSharePaymentReceipt(Map<String, dynamic> payment, Map<String, dynamic> invoice) async {
    final pdf = pw.Document();
    final date = DateTime.fromMillisecondsSinceEpoch(payment['created_at']);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('SmartBiz Pro', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue600)),
                      pw.Text('OFFICIAL RECEIPT'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Receipt #: REC-${payment['id'].toString().substring(0, 8).toUpperCase()}'),
                      pw.Text('Date: ${DateFormat('MMM dd, yyyy').format(date)}'),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Text('Received From:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(invoice['customer_full_name'] ?? 'Valued Customer'),
              pw.SizedBox(height: 20),
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                child: pw.Column(
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Amount Received:'),
                        pw.Text('TZS ${payment['amount']}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
                      ],
                    ),
                    pw.Divider(),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Payment Method:'),
                        pw.Text(payment['payment_method'] ?? 'N/A'),
                      ],
                    ),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Reference Invoice:'),
                        pw.Text('#INV-${invoice['id'].toString().substring(0, 8).toUpperCase()}'),
                      ],
                    ),
                  ],
                ),
              ),
              pw.Spacer(),
              pw.Center(child: pw.Text('Thank you for your payment!')),
            ],
          );
        },
      ),
    );

    final bytes = await pdf.save();
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/REC-${payment['id']}.pdf');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles([XFile(file.path)], text: 'Here is your Payment Receipt');
  }

  Future<void> printDocument(Map<String, dynamic> sale) async {
    final pdf = pw.Document();
    // ... (Same PDF generation logic as above, ideally refactored)
    // For now, I'll just reuse the sharing logic or implement Printing.layoutPdf
  }
}
